language: node_js
node_js:
  - 14
script:
  - yarn test
notifications:
  email:
    recipients:
      - ufrapl21@gmail.com
      - emanoeljhones@gmail.com
      on_success: always
      on_failure: always
